os: osx
language: node_js
node_js:
- lts/*
cache: yarn
addons:	
  homebrew:	
    packages:	
    - p7zip
before_install:
- npm install -g pkg@4.3.8
before_deploy:
- git config --local user.name "Mario Loriedo"
- git config --local user.email "mario.loriedo@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
- export SHORT_SHA1=$(git rev-parse --short HEAD)
- git tag $TRAVIS_TAG
- sed -i sed "s#version\":\ \"\(.*\)\",#version\":\ \"\1-${SHORT_SHA1}\",#g" package.json
- yarn pack
- mkdir ${TRAVIS_BUILD_DIR}/packages
- npx oclif-dev pack -t darwin-x64
deploy:
  provider: releases
  api-key: $GITHUB_AUTH_TOKEN
  file_glob: true
  file:
  - "dist/chectl-v*/chectl-*.gz"
  - "${TRAVIS_BUILD_DIR}/packages/chectl-*"
  skip_cleanup: true
  on:
    repo: benoitf/chectltest
    tags: false
jobs:
  include:
  - stage: "Releases from master: next channel"
    if: branch = master
    script: skip
    before_deploy:
    - echo "this is before_deploy in case of master branch"
  - stage: "Releases from 'release' branch: stable channel"
    if: branch = release
    before_deploy:
    - echo "this is before_deploy in case of release branch"
