os: osx
language: node_js
node_js:
- lts/*
cache: yarn
addons:	
  homebrew:	
    packages:	
    - p7zip
before_install:
- npm install -g pkg@4.3.8
deploy:
  provider: releases
  api-key: $GITHUB_AUTH_TOKEN
  file_glob: true
  name: $CHECTL_VERSION
  file:
  - "dist/chectl-v*/chectl-*.gz"
  - "${TRAVIS_BUILD_DIR}/packages/chectl-*"
  skip_cleanup: true
  on:
    repo: benoitf/chectltest
    tags: false
jobs:
  include:
  - stage: "Configuration for releases from master branch: next channel"
    if: branch = master
    script: skip
    before_deploy:
    - echo "this is before_deploy in case of master branch"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
    - export SHORT_SHA1=$(git rev-parse --short HEAD)
    - export CHECTL_VERSION=${SHORT_SHA1}
  - stage: "Configuration for releases from 'release' branch: stable channel"
    if: branch = release
    before_deploy:
    - echo "this is before_deploy in case of release branch"
  - stage: "Build artifacts"
    before_deploy:
    - echo "this is before_deploy for building artifacts"
    - git config --local user.name "Mario Loriedo"
    - git config --local user.email "mario.loriedo@gmail.com"
    - git tag $TRAVIS_TAG
    - sed -i sed "s#version\":\ \"\(.*\)\",#version\":\ \"\1-${CHECTL_VERSION}\",#g" package.json
    - yarn pack
    - mkdir ${TRAVIS_BUILD_DIR}/packages
    - npx oclif-dev pack -t darwin-x64
