os: osx
language: node_js
node_js:
- lts/*
cache: yarn
before_install:
- npm install -g pkg@4.3.8
before_deploy:
- brew update
- brew install p7zip
- git config --local user.name "Mario Loriedo"
- git config --local user.email "mario.loriedo@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
- export SHORT_SHA1=$(git rev-parse --short HEAD)
- git tag $TRAVIS_TAG
- sed -i sed "s#version\":\ \"\(.*\)\",#version\":\ \"\1-${SHORT_SHA1}\",#g" package.json
- yarn pack
- mkdir ${TRAVIS_BUILD_DIR}/packages
- pkg . -t node10-linux-x64,node10-macos-x64,node10-win-x64 --options max_old_space_size=1024 --out-path ${TRAVIS_BUILD_DIR}/packages/
- npx oclif-dev pack
deploy:
  provider: releases
  api-key: $GITHUB_AUTH_TOKEN
  file_glob: true
  file:
  - "dist/chectl-v*/chectl-*.gz"
  - "${TRAVIS_BUILD_DIR}/packages/chectl-*"
  skip_cleanup: true
  on:
    repo: benoitf/chectltest
    tags: false
